version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hamed
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hamed
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - "7000:5432"
  pg_slave:
    build: ./slave
    volumes:
      - pg_slave_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hamed
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hamed
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - "7001:5432"
volumes:
  pg_master_data:
  pg_slave_data: